api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "free-item"
type = "function"
uid = "c3d040e1-b5f4-047b-d6bb-af36161fc716501fe8ad"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
