api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "bundle-discount"
type = "function"
uid = "208e9edf-8b9b-6b74-3f3a-539fdede2328f859a084"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
